# Generated by Django 4.2.7 on 2023-12-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientId', models.EmailField(default=None, max_length=50)),
                ('PatientName', models.CharField(max_length=50)),
                ('PatientAge', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('PatientMobileNumber', models.IntegerField()),
                ('PatientLocation', models.CharField(max_length=50)),
                ('HospitalBranch', models.CharField(max_length=50)),
                ('DoctorName', models.CharField(max_length=50)),
                ('Oppoinment', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('UserEmail', models.CharField(max_length=50)),
                ('UserMobileNumber', models.CharField(max_length=10)),
                ('UserPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
