# Generated by Django 4.2.7 on 2023-12-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_patientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='PatientId',
            new_name='patient_id',
        ),
    ]
