# Generated by Django 4.2.7 on 2023-12-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_patientid_patient_patient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
